name: Node CI


on: [push]


jobs:
  build:


    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [12.x]


    steps:
    - uses: nanasess/setup-chromedriver@master
      with:
       chromedriver-version: '88.0.4324.27'
    - run: |
       export DISPLAY=:99
       chromedriver --url-base=/wd/hub &
       sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
    
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run start
        npm run test
      env:
        CI: true