name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
        - name: Checkout
          steps:
          - uses: actions/checkout@v2
          - uses: nanasess/setup-chromedriver@master
            with:
              # Optional: do not specify to match Chrome's version
              chromedriver-version: '88.0.4324.96'
          - run: |
              export DISPLAY=:99
              chromedriver --url-base=/wd/hub &
              sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

        - name: Install
          steps:
            - run: npm install
            - run: npm run start
        - name: Test
          steps:
            - run: npm run test